services:
  - type: web
    name: procesia-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
