"""'add_macro_sequence_flows'

Revision ID: f613bf0571fe
Revises: 0004
Create Date: 2026-06-22 20:56:14.775642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f613bf0571fe'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_sequence_flows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('macroprocess_id', sa.BigInteger(), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('target_ref', sa.String(length=60), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['macroprocess_id'], ['macroprocesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_sequence_flows')
    # ### end Alembic commands ###
